apiVersion: v1
kind: Pod
metadata:
  name: did-finder
  namespace: servicex
  labels:
    app: did-finder
spec:
  volumes:
  - name: x509-certs-volume
    secret:
      secretName: cert-secret
      items:
      - key: userkey
        path: userkey.pem
        mode: 256 
      - key: usercert
        path: usercert.pem

  containers:
  - name: did-finder
    image: sslhep/servicex-did-finder:latest
    command: ["sleep"]
    args: ["36500000"]
    volumeMounts:
    - name: x509-certs-volume
      mountPath: "/.globus/"
      readOnly: true

  restartPolicy: Never